# Generated by Django 4.2.30 on 2026-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0002_add_form_input_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='default_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='is_multiselect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='is_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='max_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='min_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='placeholder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='value_step',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldoption',
            name='is_preselected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldoption',
            name='option_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldoption',
            name='option_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forminputtype',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='default_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='is_multiselect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='is_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='max_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='min_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='placeholder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='value_step',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfieldoption',
            name='is_preselected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfieldoption',
            name='option_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfieldoption',
            name='option_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforminputtype',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalformsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformsection',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserformdata',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserformdata',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserformdata',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserformsubmission',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstep',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstep',
            name='responsibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstep',
            name='step_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstep',
            name='workflow_role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstepapproval',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstepapproval',
            name='is_reverted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstepapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstepavailablefield',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userformdata',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userformdata',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userformdata',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userformsubmission',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='responsibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='workflow_role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstepapproval',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstepapproval',
            name='is_reverted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstepapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstepavailablefield',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
