# Generated by Django 4.2.30 on 2026-06-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0003_alter_formfield_default_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkflowstepavailablefield',
            name='workflow_step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_workflow.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowstepavailablefield',
            name='workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workflow_step_available_field_workflow_step', to='service_workflow.workflowstep'),
        ),
    ]
