# Generated by Django 4.2.30 on 2026-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0005_remove_historicaluserformdata_interactive_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublicservice',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicservice',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
