# Generated by Django 4.2.30 on 2026-06-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0006_alter_historicalpublicservice_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkflowstepapproval',
            name='final_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstepapproval',
            name='final_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
