# Generated by Django 4.2.30 on 2026-06-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0007_historicalworkflowstepapproval_final_approved_and_more'),
        ('service_workflow', '0008_add_form_input_types'),
    ]

    operations = [
    ]
