# Generated by Django 4.2.30 on 2026-06-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0009_merge_20260624_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkflowstepapproval',
            name='is_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstepapproval',
            name='is_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
