# Generated by Django 4.2.30 on 2026-08-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0010_historicalworkflowstepapproval_is_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='value_step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='value_step',
            field=models.TextField(blank=True, null=True),
        ),
    ]
