# Generated by Django 4.2.30 on 2026-08-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0012_formfield_form_field_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='form_field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_field_group_form_field', to='service_workflow.formfieldgroup'),
        ),
        migrations.AlterField(
            model_name='formfieldgroup',
            name='form_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_field_group_form_section', to='service_workflow.formfieldgroup'),
        ),
        migrations.AlterField(
            model_name='formfieldoption',
            name='form_field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_field_option_group_form_field', to='service_workflow.formfieldgroup'),
        ),
        migrations.AlterField(
            model_name='historicalformfield',
            name='form_field_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_workflow.formfieldgroup'),
        ),
        migrations.AlterField(
            model_name='historicalformfieldgroup',
            name='form_section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_workflow.formfieldgroup'),
        ),
        migrations.AlterField(
            model_name='historicalformfieldoption',
            name='form_field_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_workflow.formfieldgroup'),
        ),
        migrations.AlterField(
            model_name='historicaluserformdata',
            name='form_field_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_workflow.formfieldgroup'),
        ),
        migrations.AlterField(
            model_name='userformdata',
            name='form_field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_form_data_form_field_group', to='service_workflow.formfieldgroup'),
        ),
    ]
