# Generated by Django 4.2.30 on 2026-08-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_workflow', '0013_alter_formfield_form_field_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldgroup',
            name='form_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_field_group_form_section', to='service_workflow.formsection'),
        ),
        migrations.AlterField(
            model_name='historicalformfieldgroup',
            name='form_section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_workflow.formsection'),
        ),
    ]
